# This workflow is triggered when a pull request is merged and the label 'release' is present.
# It opens a pull request to backport the changes from main to develop.
name: Create backport pull request

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  create-backport-pull-request:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-24.04

    steps:

        - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
          with:
            ref: develop

        # See https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
        - name: Fetch main branch
          run: |
            git fetch origin main:main
            git reset --hard main

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
          with:
            commit-message: 'chore: backport main to develop'
            title: Backport main to develop
            branch: chore/backport-main-to-develop
            base: develop
            labels: skip-changelog
