name: Create hotfix pull request

on:
  workflow_dispatch:
    inputs:
      changelog-message:
        type: string
        description: The message to add to the changelog
        required: true

jobs:

  create-hotfix-pull-request:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main

      - name: Release drafter
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release draft
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: "${{ steps.release-drafter.outputs.id }}",
              draft: true,
              body: "### üêõ Bug Fixes\n ${{ inputs.changelog-message }}\n"
            });

      - name: Update CHANGELOG.md file
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1.12.0
        with:
          latest-version: ${{ steps.release-drafter.outputs.tag_name }}
          release-notes: "### üêõ Bug Fixes\n ${{ inputs.changelog-message }}\n"

      - name: Update other files
        run: |
          ./scripts/update-files-with-release-version.sh ${{ steps.release-drafter.outputs.tag_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: 'chore: update version'
          title: Release ${{ steps.release-drafter.outputs.tag_name }}
          body: |
            Update version to ${{ steps.release-drafter.outputs.tag_name }}
    
            ### Checklist of actions to be done before merging
            - [ ] Review and update the CHANGELOG.md if needed
            - [ ] Review and update the Github release draft if needed
            - [ ] Review the files updated with the new version number in the commit named "chore: update version"
          branch: hotfix/${{ steps.release-drafter.outputs.tag_name }}
          base: main
          labels: hotfix, release

